"""Initial migration

Revision ID: 3f4f72b839cf
Revises: 
Create Date: 2025-12-06 19:43:07.340045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f4f72b839cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprendices', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_colegio'))
        batch_op.drop_index(batch_op.f('idx_grupo'))
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.drop_index(batch_op.f('usuario_id'))
        batch_op.create_index(batch_op.f('ix_aprendices_colegio_id'), ['colegio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aprendices_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aprendices_usuario_id'), ['usuario_id'], unique=True)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_index(batch_op.f('idx_tabla'))
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.create_index(batch_op.f('ix_auditoria_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_tabla'), ['tabla'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_nombre'))
        batch_op.create_index(batch_op.f('ix_colegios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_colegios_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('fecha_validacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_matricula'))
        batch_op.drop_index(batch_op.f('idx_tipo'))
        batch_op.drop_index(batch_op.f('idx_validado'))
        batch_op.create_index(batch_op.f('ix_documentos_matricula_id'), ['matricula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_tipo_documento'), ['tipo_documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_validado'), ['validado'], unique=False)

    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_colegio'))
        batch_op.drop_index(batch_op.f('idx_programa'))
        batch_op.create_index(batch_op.f('ix_grupos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupos_colegio_id'), ['colegio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupos_programa_id'), ['programa_id'], unique=False)

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.alter_column('fecha_envio',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fecha_validacion_docente',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fecha_validacion_admin',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_aprendiz'))
        batch_op.drop_index(batch_op.f('idx_estado'))
        batch_op.drop_index(batch_op.f('idx_fecha_envio'))
        batch_op.create_index(batch_op.f('ix_matriculas_aprendiz_id'), ['aprendiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_fecha_envio'), ['fecha_envio'], unique=False)

    with op.batch_alter_table('mensajes_contacto', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_index(batch_op.f('idx_leido'))
        batch_op.create_index(batch_op.f('ix_mensajes_contacto_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_contacto_leido'), ['leido'], unique=False)

    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_destacado'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.create_index(batch_op.f('ix_novedades_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_novedades_destacado'), ['destacado'], unique=False)
        batch_op.create_index(batch_op.f('ix_novedades_fecha_publicacion'), ['fecha_publicacion'], unique=False)

    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_activo'))
        batch_op.drop_index(batch_op.f('idx_codigo'))
        batch_op.create_index(batch_op.f('ix_programas_activo'), ['activo'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('documento'))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_documento'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_rol'))
        batch_op.create_index(batch_op.f('ix_usuarios_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', mysql.VARCHAR(length=200), sa.Computed("(concat(`nombres`,' ',`apellidos`))", persisted=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_documento'))
        batch_op.create_index(batch_op.f('idx_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('documento'), ['documento'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programas_activo'))
        batch_op.create_index(batch_op.f('idx_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novedades_fecha_publicacion'))
        batch_op.drop_index(batch_op.f('ix_novedades_destacado'))
        batch_op.drop_index(batch_op.f('ix_novedades_activo'))
        batch_op.create_index(batch_op.f('idx_fecha'), ['fecha_publicacion'], unique=False)
        batch_op.create_index(batch_op.f('idx_destacado'), ['destacado'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('mensajes_contacto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_contacto_leido'))
        batch_op.drop_index(batch_op.f('ix_mensajes_contacto_created_at'))
        batch_op.create_index(batch_op.f('idx_leido'), ['leido'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_fecha_envio'))
        batch_op.drop_index(batch_op.f('ix_matriculas_estado'))
        batch_op.drop_index(batch_op.f('ix_matriculas_aprendiz_id'))
        batch_op.create_index(batch_op.f('idx_fecha_envio'), ['fecha_envio'], unique=False)
        batch_op.create_index(batch_op.f('idx_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('idx_aprendiz'), ['aprendiz_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_validacion_admin',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('fecha_validacion_docente',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('fecha_envio',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_programa_id'))
        batch_op.drop_index(batch_op.f('ix_grupos_colegio_id'))
        batch_op.drop_index(batch_op.f('ix_grupos_activo'))
        batch_op.create_index(batch_op.f('idx_programa'), ['programa_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_colegio'), ['colegio_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_validado'))
        batch_op.drop_index(batch_op.f('ix_documentos_tipo_documento'))
        batch_op.drop_index(batch_op.f('ix_documentos_matricula_id'))
        batch_op.create_index(batch_op.f('idx_validado'), ['validado'], unique=False)
        batch_op.create_index(batch_op.f('idx_tipo'), ['tipo_documento'], unique=False)
        batch_op.create_index(batch_op.f('idx_matricula'), ['matricula_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_validacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colegios_nombre'))
        batch_op.drop_index(batch_op.f('ix_colegios_activo'))
        batch_op.create_index(batch_op.f('idx_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('idx_activo'), ['activo'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_tabla'))
        batch_op.drop_index(batch_op.f('ix_auditoria_created_at'))
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tabla'), ['tabla'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('aprendices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aprendices_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_aprendices_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_aprendices_colegio_id'))
        batch_op.create_index(batch_op.f('usuario_id'), ['usuario_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_grupo'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_colegio'), ['colegio_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###
